// Mock/demo data only — no backend, nothing here is generated by a real AI model.

export type DramaProject = {
  id: string;
  title: string;
  cover: string;
  status: "in_progress" | "completed" | "draft";
  synopsis: string;
  style: string;
  episodeCount: number;
  updatedAt: string;
};

export type VideoProject = {
  id: string;
  title: string;
  status: "draft" | "generating" | "completed" | "published";
  template: string;
  ratio: string;
  updatedAt: string;
};

export type Episode = {
  id: number;
  title: string;
  summary: string;
};

export const dramaProjects: DramaProject[] = [
  {
    id: "1",
    title: "Ngọn Hải Đăng Cuối Cùng",
    cover: "from-indigo-400 to-slate-700",
    status: "in_progress",
    synopsis:
      "Trên hòn đảo nhỏ Vareth, nơi thần biển cả và loài người từng giao ước, Lina — một cô gái giữ đèn hải đăng — phát hiện ra bí mật khiến cả hòn đảo chìm trong bóng tối suốt 100 năm...",
    style: "Hình ảnh chân thực, tông màu lạnh, không khí huyền bí",
    episodeCount: 12,
    updatedAt: "2026-09-08",
  },
  {
    id: "2",
    title: "Quán Trọ Giữa Hai Thế Giới",
    cover: "from-amber-400 to-rose-600",
    status: "draft",
    synopsis:
      "Một quán trọ nhỏ ven đường chỉ mở cửa lúc nửa đêm, phục vụ cho những vị khách không thuộc về thế giới này...",
    style: "Phong cách anime, ấm áp, giả tưởng nhẹ nhàng",
    episodeCount: 8,
    updatedAt: "2026-09-05",
  },
  {
    id: "3",
    title: "Đế Chế Rồng Sắt",
    cover: "from-emerald-500 to-teal-800",
    status: "completed",
    synopsis:
      "Khi Đế chế Rồng Sắt sụp đổ, ba phe phái tranh giành báu vật cuối cùng có thể hồi sinh cả một nền văn minh đã mất.",
    style: "Sử thi, võ thuật, hình ảnh điện ảnh",
    episodeCount: 16,
    updatedAt: "2026-08-28",
  },
];

export const episodes: Episode[] = [
  { id: 1, title: "Tập 1", summary: "Cơn bão bất thường ập đến bờ biển phía Bắc." },
  { id: 2, title: "Tập 2", summary: "Lina tìm thấy cuốn nhật ký của người giữ đèn tiền nhiệm." },
  { id: 3, title: "Tập 3", summary: "Một người lạ dạt vào bờ, mang theo lời nguyền cổ xưa." },
  { id: 4, title: "Tập 4", summary: "Bí mật về giao ước với thần biển dần hé lộ." },
  { id: 5, title: "Tập 5", summary: "Cuộc rượt đuổi trên những vách đá dựng đứng." },
  { id: 6, title: "Tập 6", summary: "Kẻ thù trở thành đồng minh bất đắc dĩ." },
  { id: 7, title: "Tập 7", summary: "Dấu vết của ngọn hải đăng nguyên bản được tìm thấy." },
  { id: 8, title: "Tập 8", summary: "Thần biển thức giấc, cơn thịnh nộ nhấn chìm hòn đảo." },
  { id: 9, title: "Tập 9", summary: "Sự thật về lời nguyền khiến tất cả đảo lộn." },
  { id: 10, title: "Tập 10", summary: "Ba phe phái cùng tranh giành quyền kiểm soát ngọn đèn." },
  { id: 11, title: "Tập 11", summary: "Lina hy sinh thân mình để giữ ngọn lửa không tắt." },
  { id: 12, title: "Tập 12", summary: "Bình minh mới trên hòn đảo Vareth." },
];

export const assetCategories = ["Vai trò", "Bối cảnh", "Đạo cụ", "Âm sắc"] as const;

export const characterAssets = [
  { id: "c1", name: "Lina", role: "Nhân vật chính", tag: "Hình ảnh thực tế" },
  { id: "c2", name: "Ông Corvin", role: "Người giữ đèn tiền nhiệm", tag: "Hình ảnh thực tế" },
  { id: "c3", name: "Thần Biển Ashka", role: "Phản diện / Thần thoại", tag: "Giả tưởng" },
];

export const videoProjects: VideoProject[] = [
  {
    id: "336",
    title: "Sự hình thành của lỗ đen: Từ ngôi sao đến hố đen",
    status: "draft",
    template: "Cảm giác như phim người đóng",
    ratio: "16:9",
    updatedAt: "2026-09-08 21:09",
  },
  {
    id: "337",
    title: "Vì sao san hô đang biến mất?",
    status: "completed",
    template: "Phỏng vấn đường phố",
    ratio: "9:16",
    updatedAt: "2026-09-02 10:14",
  },
];

export const styleTemplates = [
  { id: "s1", name: "Giới thiệu dự án mã nguồn mở", ratio: "9:16" },
  { id: "s2", name: "Những cảnh làm việc thực tế", ratio: "16:9" },
  { id: "s3", name: "Phỏng vấn & phát sóng trên đường phố", ratio: "9:16" },
  { id: "s4", name: "Bản demo trực tiếp trên máy tính", ratio: "16:9" },
  { id: "s5", name: "Hình ảnh và văn bản hiển thị dọc", ratio: "9:16" },
  { id: "s6", name: "Cảm giác như phim người đóng", ratio: "16:9" },
];

export const characterStyles = [
  { id: "real", name: "Hình ảnh thực tế", desc: "Kết cấu con người chân thực" },
  { id: "anime", name: "Nhân vật anime", desc: "Nhân vật Anime/Manga" },
  { id: "silhouette", name: "Hình bóng", desc: "Biểu hiện hình bóng trừu tượng" },
  { id: "none", name: "Không có nhân vật", desc: "Chỉ có cảnh thuần túy" },
];

export const voiceOptions = [
  { id: "v1", name: "Giọng nữ ấm áp — Kể chuyện", gender: "Giọng nữ" },
  { id: "v2", name: "Giọng nữ ngọt ngào — Tâm tình", gender: "Giọng nữ" },
  { id: "v3", name: "Giọng nữ vui tươi — Phong cách đô thị", gender: "Giọng nữ" },
  { id: "v4", name: "Minh — Giọng nam trầm ấm", gender: "Giọng nam" },
  { id: "v5", name: "An — Giọng nam trẻ trung", gender: "Giọng nam" },
];

export const aiTools = [
  { id: "t2i", name: "Văn Sinh Tú", desc: "Tạo hình ảnh chất lượng cao bằng cách sử dụng mô tả văn bản.", icon: "image" },
  { id: "i2i", name: "Hình ảnh", desc: "Tải lên ảnh tham khảo và tạo các biến thể với cùng phong cách.", icon: "sparkles" },
  { id: "i2p", name: "Sản phẩm được tạo ra từ hình ảnh", desc: "Tạo ảnh nền trắng và ảnh sản phẩm chỉ với một cú nhấp chuột.", icon: "package" },
  { id: "t2v", name: "Video Văn Sinh", desc: "Tạo video ngắn từ kịch bản", icon: "play" },
  { id: "v2v", name: "Video sản xuất video", desc: "Biến đổi phong cách và chuyển động của các video hiện có", icon: "film" },
  { id: "ecom", name: "công cụ thương mại điện tử", desc: "Một bộ sưu tập các công cụ nhỏ như ghép ảnh chính và bố cục chi tiết sản phẩm.", icon: "layers" },
];

export type ToolField =
  | { kind: "upload"; label: string }
  | { kind: "textarea"; label: string; placeholder?: string; optional?: boolean }
  | { kind: "chips"; label: string; options: string[] }
  | { kind: "cards"; label: string; options: { title: string; desc?: string }[] };

export type ToolDetail = {
  id: string;
  intro: string;
  fields: ToolField[];
  submitLabel: string;
};

export const toolDetails: Record<string, ToolDetail> = {
  t2i: {
    id: "t2i",
    intro: "Mô tả hình ảnh bằng văn bản, chọn kích thước hình ảnh, và hình ảnh sẽ được tạo ra.",
    fields: [
      { kind: "textarea", label: "Từ khóa", placeholder: "Hãy mô tả chủ thể, khung cảnh, ánh sáng và phong cách..." },
      { kind: "textarea", label: "Từ gợi ý đảo ngược", placeholder: "Nội dung không mong muốn, chẳng hạn như văn bản, hình mờ, v.v.", optional: true },
      { kind: "chips", label: "Khung", options: ["1:1", "16:9", "9:16"] },
    ],
    submitLabel: "phát ra",
  },
  i2i: {
    id: "i2i",
    intro: "Tải lên hình ảnh tham khảo và mô tả các bộ phận bạn muốn giữ lại hoặc thay đổi.",
    fields: [
      { kind: "upload", label: "Hình ảnh tham khảo" },
      { kind: "textarea", label: "Từ khóa", placeholder: "Giữ nguyên chủ đề chính, sau đó chuyển sang cảnh đêm mang phong cách điện ảnh…" },
      { kind: "chips", label: "Sự tương đồng", options: ["Thấp", "ở giữa", "cao"] },
    ],
    submitLabel: "phát ra",
  },
  i2p: {
    id: "i2p",
    intro: "Tải lên hình ảnh sản phẩm, chọn nền trắng, cảnh vật hoặc hình ảnh dài để hiển thị chi tiết sản phẩm.",
    fields: [
      { kind: "upload", label: "Hình ảnh sản phẩm" },
      {
        kind: "cards",
        label: "Loại đầu ra",
        options: [
          { title: "Hình ảnh nền trắng" },
          { title: "Sơ đồ cảnh" },
          { title: "Xem chi tiết bằng hình ảnh dài." },
        ],
      },
      { kind: "textarea", label: "Mô tả bổ sung (tùy chọn)", optional: true },
    ],
    submitLabel: "Tạo ảnh sản phẩm",
  },
  t2v: {
    id: "t2v",
    intro:
      "Sau khi điền đầy đủ kịch bản, một khung hình tĩnh sẽ được tạo ra trước, sau đó là một video ngắn (khoảng 1-3 phút) sẽ được tạo.",
    fields: [
      { kind: "textarea", label: "Kịch bản video" },
      { kind: "chips", label: "Khoảng thời gian", options: ["5 giây", "10 giây", "15 giây"] },
      { kind: "chips", label: "Khung", options: ["16:9", "9:16"] },
    ],
    submitLabel: "Tạo video",
  },
  v2v: {
    id: "v2v",
    intro: "Hãy tải lên video gốc hoặc khung hình đầu tiên, và mô tả phong cách và cường độ của chuyển động.",
    fields: [
      { kind: "upload", label: "Video nguồn / Khung hình đầu tiên" },
      { kind: "textarea", label: "Mô tả chuyển đổi" },
      { kind: "chips", label: "Cường độ tập luyện", options: ["yếu đuối", "ở giữa", "mạnh mẽ"] },
    ],
    submitLabel: "Bắt đầu chuyển đổi",
  },
  ecom: {
    id: "ecom",
    intro: "Bạn cần kết hợp ít nhất 2 hình ảnh; để tạo poster giới thiệu sản phẩm, bạn chỉ cần tải lên 1 hình ảnh sản phẩm.",
    fields: [
      { kind: "chips", label: "bộ công cụ", options: ["Ghép ảnh chính", "Bố cục chi tiết", "Poster giới thiệu sản phẩm"] },
      { kind: "upload", label: "hình ảnh" },
      { kind: "textarea", label: "Mô tả các điểm nổi bật (có thể kèm poster hoặc không)", optional: true },
    ],
    submitLabel: "Bắt đầu làm",
  },
};

export const topUpAmounts = [50000, 100000, 200000, 500000, 1000000, 2000000];

export const videoTemplates = [
  { id: "tpl1", name: "Khoa học phổ biến", desc: "Giải thích một hiện tượng khoa học bằng hình ảnh trực quan." },
  { id: "tpl2", name: "Phỏng vấn nhân vật", desc: "Dựng lại cuộc phỏng vấn dạng hỏi đáp, phong cách tài liệu." },
  { id: "tpl3", name: "Giới thiệu sản phẩm", desc: "Video ngắn quảng bá tính năng và lợi ích sản phẩm." },
  { id: "tpl4", name: "Kể chuyện lịch sử", desc: "Tường thuật một sự kiện hoặc nhân vật lịch sử." },
  { id: "tpl5", name: "Tóm tắt bài viết", desc: "Chuyển bài blog dài thành video dọc dễ xem." },
  { id: "tpl6", name: "Trống — tự viết kịch bản", desc: "Bắt đầu từ một trang trắng, tự viết toàn bộ kịch bản." },
];

// ---- Per-episode shot editor (the detailed "AI phân cảnh" screen) ----

export type SegmentLineTag = "subtitle_config" | "bgm" | "dialogue" | "visual";

export type SegmentLine = {
  id: string;
  durationSec: number;
  tag: SegmentLineTag;
  character?: string;
  direction?: string; // parenthetical emotion/action note
  shotType?: string; // for visual lines: Toàn cảnh, Trung cảnh, Cận cảnh, Đặc tả...
  text: string;
};

export type Segment = {
  id: number;
  title: string; // "Đoạn 1"
  durationSec: number;
  status: "pending" | "generating" | "done" | "failed";
  lines: SegmentLine[];
};

const line = (
  id: string,
  durationSec: number,
  tag: SegmentLineTag,
  text: string,
  extra: Partial<SegmentLine> = {}
): SegmentLine => ({ id, durationSec, tag, text, ...extra });

// Curated, hand-written segments for episode 1 — this is the level of detail
// the real per-episode editor screen shows: each line is a shot or a
// dialogue/audio cue with its own duration.
const episode1Segments: Segment[] = [
  {
    id: 1,
    title: "Đoạn 1",
    durationSec: 18,
    status: "pending",
    lines: [
      line("1-cfg", 0, "subtitle_config", "Phụ đề: căn giữa dưới · tiếng Việt · luân phiên theo câu · đồng bộ lời thoại"),
      line("1-bgm", 0, "bgm", "Nhạc nền: sóng biển xa, dây kéo dài u tịch; âm lượng thấp hơn lời thoại"),
      line("1-1", 6, "visual", "Con bão bất thường kéo đến từ ngoài khơi, mây đen cuộn thành hình xoáy trên ngọn hải đăng Vareth.", { shotType: "Toàn cảnh" }),
      line("1-2", 5, "visual", "Sóng lớn đập vào vách đá, nước bắn tung toé qua cả lớp kính cửa sổ hải đăng.", { shotType: "Cận cảnh" }),
      line("1-3", 4, "dialogue", "Đèn hải đăng chưa từng tắt một đêm nào suốt 100 năm... sao đêm nay lại chớp liên hồi thế này?", {
        character: "Lina",
        direction: "nhìn ra cửa sổ, giọng lo lắng",
      }),
      line("1-4", 3, "visual", "Ngọn lửa trong đèn hải đăng run rẩy, ánh sáng đỏ bất thường lan ra trên mặt biển.", { shotType: "Đặc tả" }),
    ],
  },
  {
    id: 2,
    title: "Đoạn 2",
    durationSec: 15,
    status: "pending",
    lines: [
      line("2-bgm", 0, "bgm", "Nhạc nền: căng thẳng nhẹ, tiếng chuông xa vọng lại"),
      line("2-1", 5, "visual", "Lina chạy xuống cầu thang xoắn ốc bằng đá của hải đăng, tay ôm chặt cuốn nhật ký cũ.", { shotType: "Trung cảnh" }),
      line("2-2", 4, "dialogue", "Cuốn nhật ký này... của người giữ đèn trước mình. Có lẽ ông ấy biết chuyện gì đang xảy ra.", {
        character: "Lina",
        direction: "tự nhủ, hơi thở gấp",
      }),
      line("2-3", 6, "visual", "Trang nhật ký mở ra, dòng chữ viết tay run rẩy: \"Nếu ngọn lửa đổi màu, giao ước đã bị phá vỡ.\"", { shotType: "Đặc tả" }),
    ],
  },
  {
    id: 3,
    title: "Đoạn 3",
    durationSec: 20,
    status: "pending",
    lines: [
      line("3-bgm", 0, "bgm", "Nhạc nền: hợp âm thấp, kéo dài, gợi cảm giác điềm báo"),
      line("3-1", 7, "visual", "Ngoài bờ đá, một bóng người bất động nằm sấp giữa đám rong biển, sóng vẫn tiếp tục vỗ vào.", { shotType: "Toàn cảnh" }),
      line("3-2", 5, "dialogue", "Có người! Có người mắc kẹt ngoài bãi đá!", {
        character: "Lina",
        direction: "hét lên, chạy về phía bờ",
      }),
      line("3-3", 4, "visual", "Lina quỳ xuống lật người lạ lại — trên cổ tay ông ta là một hình xăm giống hệt hoa văn trên tường hải đăng.", { shotType: "Cận cảnh" }),
      line("3-4", 4, "dialogue", "Hoa văn này... sao lại giống với thứ khắc trên tường phòng đèn?", {
        character: "Lina",
        direction: "sững người",
      }),
    ],
  },
];

const genericSegments = (episodeId: number): Segment[] =>
  Array.from({ length: 4 }, (_, i) => {
    const n = i + 1;
    return {
      id: n,
      title: `Đoạn ${n}`,
      durationSec: 12 + n * 2,
      status: "pending" as const,
      lines: [
        line(`${episodeId}-${n}-bgm`, 0, "bgm", "Nhạc nền: theo tông màu chung của dự án, âm lượng thấp hơn lời thoại"),
        line(`${episodeId}-${n}-v1`, 6, "visual", "Cảnh quay minh hoạ diễn biến chính của đoạn này, tham chiếu tài sản nhân vật/bối cảnh đã tạo.", {
          shotType: n % 2 === 0 ? "Trung cảnh" : "Toàn cảnh",
        }),
        line(`${episodeId}-${n}-d1`, 4, "dialogue", "(Lời thoại minh hoạ — chỉnh sửa trực tiếp trong khung nội dung của đoạn.)", {
          character: "Nhân vật",
          direction: "chưa xác định cảm xúc",
        }),
      ],
    };
  });

export function getSegmentsForEpisode(episodeId: number): Segment[] {
  if (episodeId === 1) return episode1Segments;
  return genericSegments(episodeId);
}

export const subtitleModel = "Mô hình được tạo tự động";
export const shotAiModel = "Seedance 2.5";
// legacy alias kept for any existing callers
export const subtitleTemplates = ["Mô hình tự tạo phụ đề.", "Ghép phụ đề hậu kỳ"];

export const videoModels = ["Seedance 2.5", "Seedance 1.5"];

export const aspectRatios = ["9:16", "16:9", "1:1"];
export const resolutions = ["480p", "720p", "1080p"];

export type SubtitleMode = {
  id: "auto" | "post";
  label: string;
  desc: string;
};
export const subtitleModes: SubtitleMode[] = [
  {
    id: "auto",
    label: "Mô hình tự tạo phụ đề.",
    desc:
      'Sau khi chuyển đổi, lời nhắc "phụ đề đồng bộ/gợi ý phụ đề" sẽ được thêm ngay lập tức vào văn bản phân cảnh hiện tại, và phụ đề sẽ được tạo trực tiếp bởi mô hình trong quá trình tạo.',
  },
  {
    id: "post",
    label: "Ghép phụ đề hậu kỳ",
    desc:
      "Sau khi chuyển đổi, các lời nhắc phụ đề trong bảng phân cảnh hiện tại sẽ bị xoá ngay lập tức; bảng phụ đề ở bên phải vẫn có thể được xem trước và xuất ra để chèn phụ đề sau này.",
  },
];

export const cameraStitchInfo = {
  title: "Chuyển đổi giữa các camera",
  optionLabel: "Hãy sử dụng khung hình cuối cùng của cảnh quay trước để kết nối",
  desc:
    "Mặc định là tắt. Khi được bật, nó sẽ tạo theo thứ tự khung hình; khi tắt, mặc định nó sẽ tạo đồng thời. Việc chuyển đổi giữa các khung hình sẽ ngay lập tức sắp xếp lại các tác vụ chưa bắt đầu; các tác vụ đã được tạo sẽ không bị ảnh hưởng. Khi có tham chiếu nhân vật/cảnh, một hình ảnh tham chiếu sẽ được đính kèm với khung hình cuối cùng (không thể trộn lẫn với first_frame).",
};

export const episodeHelpTabs = {
  transfer: {
    label: "Luật vượt qua",
    intro:
      "Video kịch bản phân cảnh được tạo ra bởi giao diện đa phương thức Seedance. Phần sau đây giải thích cách hệ thống tập hợp các kịch bản, tài nguyên và tham số thanh công cụ thành một yêu cầu.",
    sections: [
      {
        heading: "Các tham số trên thanh trên cùng → Các trường API",
        items: [
          "Mô hình → model (Seedance 2.5 / 1.5)",
          "Tỷ lệ khung hình & Độ sắc nét → ratio / resolution",
          'Thời lượng → duration: tổng thời lượng trong kịch bản (khuyến nghị 4–30 giây); dùng trường "Thời lượng" của đoạn này nếu không có thẻ @duration',
          'Kiểu video → lời nhắc "Kiểu hình ảnh" thực thi khối ràng buộc',
        ],
      },
      {
        heading: "Nội dung: mảng đa phương thức (gửi theo thứ tự)",
        items: [
          "text: toàn bộ hướng dẫn lắp ráp tự động",
          "reference_image: ảnh bìa/ảnh chính của nhân vật, cảnh, vật dụng được tham chiếu",
          "reference_audio: mẫu âm thanh nhân vật/người kể với chất giọng cố định",
        ],
      },
      {
        heading: "Thứ tự lắp ráp tự động của lời nhắc",
        items: [
          "[Ràng buộc: Phong cách hình ảnh video]",
          "[Ràng buộc: Âm thanh, phụ đề và nhạc nền]",
          "[Ràng buộc: Giọng nói nhân vật] — tên → số tham chiếu âm thanh",
          "[Ràng buộc: Ngoại hình nhân vật] — tên → số hình tham khảo",
          "[Ràng buộc: Bối cảnh] — tên → số hình tham chiếu",
          "Văn bản chính: @asset:ID → \"Tên (tham khảo Hình N)\"; @duration:N → khoảng thời gian",
        ],
      },
    ],
  },
  script: {
    label: "Viết kịch bản",
    sections: [
      {
        heading: "Thẻ thời lượng",
        items: [
          "@duration:N — đánh dấu thời lượng (giây) của một đoạn nội dung, khuyến nghị 3–12s mỗi đoạn",
          "Tổng @duration trong một đoạn không vượt quá 30 giây",
          "Gõ @ để chèn thẻ thời lượng hoặc tham chiếu tài sản",
        ],
      },
      {
        heading: "Tham chiếu tài sản",
        items: [
          "@asset:123 — tham chiếu nhân vật / cảnh / đạo cụ có ID 123 trong nội dung",
          'Nhấp vào tài sản ở khung bên trái, hoặc dòng "tài sản liên quan" của đoạn này, cũng tự động chèn tham chiếu',
          "Nhân vật được tham chiếu cần có ảnh tham khảo; nhân vật cần lồng tiếng cần gắn giọng (âm thanh tham chiếu)",
        ],
      },
      {
        heading: "Quy ước cue thường dùng",
        items: [
          "Không quay/cảnh trống: viết \"Không quay:…\" / \"Toàn cảnh:…\" / \"Đặc tả:…\" hoặc 【Hình ảnh · không lồng tiếng chỉ tiếng môi trường】; không đánh dấu thành đối thoại/lời dẫn",
          "Đối thoại: Tên nhân vật: lời thoại, hoặc 【Đối thoại · chậm rõ · đồng bộ phụ đề】",
          "Lời dẫn: 【Lời dẫn · chậm rõ · đồng bộ phụ đề】; phụ đề luân phiên theo câu, không phủ kín màn hình",
          "Giới thiệu nhân vật: nhân vật quan trọng xuất hiện lần đầu được gắn tên cạnh nhân vật đó (không phải phụ đề dưới/tiêu đề giữa màn hình)",
          "BGM: âm lượng luôn thấp hơn lời thoại",
        ],
      },
    ],
  },
  recommend: {
    label: "Khuyến nghị sử dụng",
    sections: [
      {
        heading: "Kiểm tra trước khi tạo",
        items: [
          "Kịch bản hợp lệ: thời lượng hợp lệ; cảnh trống không bị đánh dấu thành đối thoại/lời dẫn",
          'Nhân vật trong "tài sản liên quan" của đoạn đã có ảnh tham khảo; nhân vật cần thoại đã có giọng nói',
          'Xác nhận tỷ lệ khung hình, độ sắc nét, kiểu hình ảnh và mô hình trước khi bấm "phát ra"',
        ],
      },
      {
        heading: "Hàng đợi & song song",
        items: [
          "Mỗi đoạn video đi qua hàng đợi video riêng; tối đa 10 luồng song song",
          "Trong khi một đoạn đang tạo, vẫn có thể chỉnh sửa kịch bản các đoạn khác hoặc xem video đã hoàn thành",
          '"Tái lập kịch bản bằng AI" xếp hàng lần lượt tất cả các đoạn của tập này; "phát ra" từng đoạn chỉ gửi đoạn hiện tại',
        ],
      },
      {
        heading: "Nối khung hình cuối giữa các đoạn",
        items: [
          "Mặc định trả về khung hình cuối sau khi tạo thành công",
          'Khi "Chuyển đổi giữa các camera" bật: nếu đoạn có tham chiếu nhân vật/cảnh, khung hình cuối được đính kèm như reference_image; nếu không có tài nguyên tham chiếu thì dùng first_frame',
          "Âm thanh tham chiếu tự động cắt còn dưới 15 giây sau khi tổng hợp",
        ],
      },
    ],
  },
};

export const scenesSample = [
  { id: 1, title: "Cảnh mở đầu", desc: "Toàn cảnh chủ đề, câu hỏi dẫn dắt người xem.", duration: "0:00–0:08" },
  { id: 2, title: "Bối cảnh", desc: "Giải thích bối cảnh / định nghĩa cơ bản.", duration: "0:08–0:20" },
  { id: 3, title: "Diễn biến chính", desc: "Đi sâu vào nội dung chính, minh hoạ bằng hình ảnh động.", duration: "0:20–0:45" },
  { id: 4, title: "Cao trào", desc: "Điểm nhấn thú vị nhất hoặc bất ngờ nhất của chủ đề.", duration: "0:45–0:55" },
  { id: 5, title: "Kết luận", desc: "Tóm tắt ngắn gọn và lời kêu gọi hành động.", duration: "0:55–1:05" },
];
